apiVersion: v1
kind: Service
metadata:
  name: sorteador-service
  namespace: ${NAMESPACE}
  labels:
    app: sorteador
spec:
  type: ClusterIP
  selector:
    app: sorteador
  ports:
    - name: http
      port: 80
      targetPort: 5000
