apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sorteador-virtualservice
  namespace: ${NAMESPACE}
spec:
  hosts:
    - "sorteador.grupobamaq.com.br"
  gateways:
    - sorteador-gateway
  http:
    - match:
        - uri:
            prefix: /
      headers:
        request:
          set:
            x-forwarded-proto: "https"
            x-forwarded-port: "443"
      route:
        - destination:
            host: sorteador-service.${NAMESPACE}.svc.cluster.local
            port:
              number: 80