name: Workflow de Continuous Integration

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  WORKDIR: app
  AWS_REGION: us-east-1

jobs:
  build-scan-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Dockerfile Lint (Hadolint)"
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.WORKDIR }}/Dockerfile
          no-fail: true
          output-file: ${{ env.WORKDIR }}/lint-report.txt

      - name: "Upload lint-report.txt"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: ${{ env.WORKDIR }}/lint-report.txt
          retention-days: 30

      - name: Configurar credenciais AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Compila nome do repo"
        id: compile
        run: |
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          FULL_IMAGE="$( echo "${REGISTRY}/${{ vars.IMAGE_NAME }}:${{ github.sha }}" | tr '[:upper:]' '[:lower:]' )"
          echo "full_image=${FULL_IMAGE}" >> "$GITHUB_OUTPUT"

      - name: "Build da imagem"
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKDIR }}
          push: false
          load: true
          tags: ${{ steps.compile.outputs.full_image }}

      - name: "Trivy - Scan"
        id: trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.compile.outputs.full_image }}
          format: 'table'
          output: ${{ env.WORKDIR }}/trivy-report.txt
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

      - name: "Upload trivy-report.txt"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: ${{ env.WORKDIR }}/trivy-report.txt
          retention-days: 30